/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

void delay(uint32_t seconds);

int main(void)
{
	uint32_t *pRCC = (uint32_t*) 0x40021014;
	uint32_t *pGPIOEmode = (uint32_t*) 0x48001000;
	uint32_t *pGPIOEoutput = (uint32_t*) 0x48001014;

	// Enable the clock for GPIOE peripheral in the AHBENR
	*pRCC |= (1 << 21); // SET the 21st bit position

	// Configure the mode of the IO pin as output.
	*pGPIOEmode &= ~(3 << 16); // clear 16th and 17th pin (binary of 3 is 11)
	*pGPIOEmode |= 0x55550000; // set the 8th-15th pin mode to 01 general purpose output mode) -- All LEDs
//	*pGPIOEmode |= (1 << 16); // set the 8th pin mode to 01 (general purpose output mode)


	// Set the 8th bit of the output data register to make the I/O pin-8 as HIGH (1) (3,3V)
//	*pGPIOEoutput |= (1 << 8);

	while(1)
	{
		// Set the 8th-15th bit of the output data register to make the I/O pin-8 as HIGH (1) (3,3V) -- All LEDs
		*pGPIOEoutput |= 0x0000FF00;

		delay(1);

		*pGPIOEoutput &= ~(0x0000FF00);

		delay(1);
	}

}

void delay(uint32_t seconds)
{
	seconds *= 800000;
	for(uint32_t i = 0; i < seconds; i++);
}
