/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pRCC = (uint32_t*) 0x40021014;
	uint32_t *pGPIOEmode = (uint32_t*) 0x48001000;
	uint32_t *pGPIOEoutput = (uint32_t*) 0x48001014;

	// Enable the clock for GPIOE peripheral in the AHBENR
	*pRCC |= 0x00200000;

	// Configure the mode of the IO pin as output.
	*pGPIOEmode &= 0xFFFCFFFF; // clear all pins
//	*pGPIOEmode |= 0x55550000; // set the 8th-15th pin mode to 01 general purpose output mode) -- All LEDs
	*pGPIOEmode |= 0x00010000; // set the 8th pin mode to 01 (general purpose output mode)


	// Set the 8th bit of the output data register to make the I/O pin-8 as HIGH (1) (3,3V)
	*pGPIOEoutput |= 0x0100;

//	// Turn on all leds
//	*pGPIOEmode |= 0x55550000; // set the 8th-15th pin mode to 01 (general purpose output mode) -- All LEDs
//
//	// Set the 8th-15th bit of the output data register to make the I/O pin-8 as HIGH (1) (3,3V) -- All LEDs
//	*pGPIOEoutput |= 0xFFFF;

    /* Loop forever */
	for(;;);
}

