/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "peripherals.h"
#include "keys.h"

int main(void)
{
	// Enable the clock for GPIOD peripheral in the AHBENR
	pRCCE->IOPDEN = STATE_HIGH;

	// Configure the mode of the PDO, PD1, PD2, PD3 pins as output.
	pGPIODmode->MODER_0 = STATE_HIGH;
	pGPIODmode->MODER_1 = STATE_HIGH;
	pGPIODmode->MODER_2 = STATE_HIGH;
	pGPIODmode->MODER_3 = STATE_HIGH;

	// Configure the mode of the PD8, PD9, PD10, PD11 pins as input
	pGPIODmode->MODER_8 = STATE_LOW;
	pGPIODmode->MODER_9 = STATE_LOW;
	pGPIODmode->MODER_10 = STATE_LOW;
	pGPIODmode->MODER_11 = STATE_LOW;

	while(1)
	{
		setRowsHigh();
		scanRow1();
		scanRow2();
		scanRow3();
		scanRow4();
	}
}
